# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[sphinx,code_style,testing]
    - name: Pre-commit checks
      run: |
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
    # cd tests/test_commonmark && ./spec.sh
    - name: Test with pytest
      run: |
        pip install pytest
        pytest --cov=myst_parser --cov-report=
    - name: Upload to coveralls
      run: |
        pip install coveralls
        coveralls
      env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_KEY }}

  publish:

    name: Publish to PyPi
    needs: build
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Build package
        run: |
          pip install wheel
          python setup.py sdist bdist_wheel
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_KEY }}
